### ISSUE TITLE
undefined method `html_safe'

### ISSUE THREAD

**Issue by mitfik** [ai/r18n#68]
Hi,

After upgrade r18n from 0.4.14 to 1.0.0 I've got this error:

```
undefined method `html_safe' for "<span style=\"color: red\">[":String
```

I use r18n with sinatra

gem list:

```
sinatra (1.3.2)
sinatra-r18n (1.0.0,)
```
